### ISSUE TITLE
Cannot enable plugin, error

### ISSUE THREAD

**Issue by sacb0y** [s-leger/archipack#257]
Archipack version:
2.3.5
Blender version:
2.93.1
Os version:
Windows 10 21H1
Description of the issue:
Cannot enable plugin.

Got this error when enabling the latest version 
```
Python: Traceback (most recent call last):
  File "C:\Users\iadag\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\archipack_20\archipack_manipulator.py", line 4376, in poll
    return o is not None and cls.get_state(context) and o.name != "Archipack_snap_helper"
  File "C:\Users\iadag\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\archipack_20\archipack_manipulator.py", line 4380, in get_state
    return context.window_manager.archipack.auto_manipulate
AttributeError: 'WindowManager' object has no attribute 'archipack'

location: <unknown location>:-1
```

**Comment by sacb0y** [comment]
Never mind, this seems to be an issue caused when the update from 2.3.2 failed, and I tried manually installing 2.3.5.

Reloading blender then installing fixed it.
